
const asset=img=>{if(!img)return'https://diamondrestaurants.com/assets/optimized-v1/diamond-full-logo-current-lossless.webp';img=String(img);if(img.startsWith('http')||img.startsWith('data:')||img.startsWith('blob:'))return img;if(img.startsWith('/'))return 'https://diamondrestaurants.com'+img;if(img.startsWith('assets/'))return 'https://diamondrestaurants.com/'+img;if(img.includes('/'))return 'https://diamondrestaurants.com/assets/'+img;return 'https://diamondrestaurants.com/assets/images/'+img;};
async function json(p){const r=await fetch(p,{cache:'force-cache'});return await r.json();}
async function liveLinks(){try{const {firebaseConfig}=await import('./firebase-config.js'); if(!firebaseConfig?.apiKey||firebaseConfig.apiKey.includes('PASTE_')) return null; const {initializeApp,getApps}=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js'); const {getFirestore,collection,getDocs}=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js'); const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig); const db=getFirestore(app); const snap=await getDocs(collection(db,'appLinks')); const arr=[]; snap.forEach(d=>{const x=d.data()||{}; if(x.visible!==false) arr.push({id:d.id,...x});}); arr.sort((a,b)=>(Number(a.sort)||0)-(Number(b.sort)||0)||String(a.name||a.id||'').localeCompare(String(b.name||b.id||''))); return arr.length?arr:null;}catch(e){return null;}}
document.getElementById('hamb')?.addEventListener('click',()=>document.getElementById('navLinks')?.classList.toggle('open'));
const grid=document.getElementById('linkGrid');
const defaults=[
  {name:'Restaurant Order',type:'Restaurant',url:'https://diamondrestaurants.uengage.in/',buttonText:'Order Now',description:'Order restaurant favourites online.',visible:true,sort:10},
  {name:'Mega Store',type:'Mega Mart',url:'https://diamondrestaurants.uengage.in/',buttonText:'Open Store',description:'Open Diamond Mega Store portal.',visible:true,sort:20},
  {name:'Android App',type:'Android App',url:'https://play.google.com/store/apps/details?id=com.app.uengage.diamondrestaurant',buttonText:'Google Play',description:'Download Diamond Restaurants Android app.',visible:true,sort:30},
  {name:'iPhone App',type:'iPhone App',url:'https://apps.apple.com/us/app/diamond-restaurants/id6743344052',buttonText:'App Store',description:'Download Diamond Restaurants iPhone app.',visible:true,sort:40},
  {name:'Google Review',type:'Review',url:'https://search.google.com/local/writereview?placeid=ChIJsR6d57d4BTkRu6lcEKPn1Eg&source=g.page.m.dd._&laa=lu-desktop-reviews-dialog-review-solicitation',buttonText:'Write Review',description:'Share your Diamond experience.',visible:true,sort:50},
  {name:'Instagram',type:'Instagram',url:'https://www.instagram.com/diamondbakerysweetsrestaurant?igsh=MTBqZTR3dmM1ODN3ZQ==',buttonText:'Follow on Instagram',description:'Follow Diamond Bakery, Restaurant & Sweets.',visible:true,sort:60},
  {name:'Google Map',type:'Map',url:'https://maps.app.goo.gl/bGiRSi4HL8HvzwQr9?g_st=ac',buttonText:'Open Map',description:'Visit Diamond in Shimla.',visible:true,sort:70}
];
const iconFor=(l)=>{const key=`${l.type||''} ${l.name||''}`.toLowerCase(); if(key.includes('restaurant')) return 'assets/icons/menu.svg'; if(key.includes('mega')||key.includes('store')||key.includes('mart')) return 'assets/icons/cart-green.svg'; if(key.includes('android')) return 'assets/icons/app-link.svg'; if(key.includes('play')) return 'assets/icons/app-link.svg'; if(key.includes('iphone')||key.includes('apple')) return 'assets/icons/app-link.svg'; if(key.includes('review')) return 'assets/icons/google-review-clean.png'; if(key.includes('instagram')) return 'assets/icons/instagram-clean.png'; if(key.includes('facebook')) return 'assets/icons/facebook-clean.png'; if(key.includes('whatsapp')) return 'assets/icons/whatsapp.svg'; if(key.includes('telephone')||key.includes('phone')) return 'assets/icons/phone.svg'; if(key.includes('mobile')) return 'assets/icons/mobile.svg'; if(key.includes('map')) return 'assets/icons/location.svg'; return 'assets/icons/app-link.svg';};
const clsFor=(l)=>{const key=`${l.type||''} ${l.name||''}`.toLowerCase(); if(key.includes('mega')||key.includes('store')||key.includes('mart')) return ' megaLink'; if(key.includes('review')) return ' reviewLink'; if(key.includes('map')) return ' mapLink'; if(key.includes('instagram')) return ' instaLink'; return '';};
function draw(links){ if(!grid) return; grid.innerHTML=links.filter(x=>x.visible!==false).sort((a,b)=>(a.sort||0)-(b.sort||0)).map(l=>`<article class="linkCard${clsFor(l)}"><div class="linkIcon"><img loading="lazy" decoding="async" src="${iconFor(l)}" alt=""></div><h3>${l.name}</h3><p>${l.description||''}</p><a class="btn btnGold" href="${l.url}" target="_blank" rel="noopener" aria-label="${l.buttonText||'Open'} ${l.name}">${l.buttonText||'Open'}</a></article>`).join('');}
draw(defaults);
(async()=>{try{const links=await liveLinks() || await json('data/app-links.json'); if(links?.length) draw(links);}catch(e){draw(defaults);}})();
